In [2]:
import numpy as np
arr = np.arange(10,21)
print(arr)
print(arr[0:3])
# print(arr[length]-1)
arr[10] = 100;
arr

[10 11 12 13 14 15 16 17 18 19 20]
[10 11 12]


array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19, 100])

In [4]:
a = np.arange(1,11)
print(a)
sli = a[1:11:2]
print(sli)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


In [5]:
sli[0] = 100
print(sli)
print(a)

[100   4   6   8  10]
[  1 100   3   4   5   6   7   8   9  10]


### Task 3

In [2]:
three = np.random.randint(1,9,size= (3,3))
three

array([[6, 5, 5],
       [1, 5, 1],
       [3, 4, 2]])

In [3]:
three[1,2]

1

In [4]:
three[:,1]

array([5, 5, 4])

### Task 4

In [7]:
random = np.random.randint(0,50, size=(4,2))
random

array([[23, 44],
       [45, 11],
       [18, 14],
       [35, 13]])

In [8]:
print("shape", random.shape)
print("size", random.size)
print("dimentions" , random.ndim)

shape (4, 2)
size 8
dimentions 2


### Task 5

In [9]:
zero = np.zeros(5)
zero


array([0., 0., 0., 0., 0.])

In [11]:
identity = np.eye(3,3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
evenly = np.linspace(0,100,10)
evenly

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

#### Task 6

In [4]:
arr = np.array([8,2,5,1,7])
arr.sort(kind="quicksort")
print(arr)

[1 2 5 7 8]


In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.concatenate(arr1,arr2)

TypeError: only integer scalar arrays can be converted to a scalar index

### Task 7

In [16]:
array1d = np.array([1,2,3,4,5,6])
print(array1d.size)
arra2 = array1d.reshape((2,3))
print(arra2)
print(array1d)

6
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
