In [2]:
import numpy as np
arr = np.arange(10,21)
print(arr)
print(arr[0:3])
# print(arr[length]-1)
arr[10] = 100;
arr

[10 11 12 13 14 15 16 17 18 19 20]
[10 11 12]


array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19, 100])

In [3]:
a = np.arange(1,11)
print(a)
sli = a[1:11:2]
print(sli)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


In [4]:
sli[0] = 100
print(sli)
print(a)

[100   4   6   8  10]
[  1 100   3   4   5   6   7   8   9  10]


### Task 3

In [5]:
three = np.random.randint(1,9,size= (3,3))
three

array([[1, 8, 3],
       [3, 1, 3],
       [5, 3, 3]])

In [6]:
three[1,2]

3

In [7]:
three[:,1]

array([8, 1, 3])

### Task 4

In [8]:
random = np.random.randint(0,50, size=(4,2))
random

array([[32, 19],
       [27, 32],
       [45, 11],
       [40, 39]])

In [9]:
print("shape", random.shape)
print("size", random.size)
print("dimentions" , random.ndim)

shape (4, 2)
size 8
dimentions 2


### Task 5

In [10]:
zero = np.zeros(5)
zero


array([0., 0., 0., 0., 0.])

In [11]:
identity = np.eye(3,3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
evenly = np.linspace(0,100,10)
evenly

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

#### Task 6

In [13]:
arr = np.array([8,2,5,1,7])
arr.sort(kind="quicksort")
print(arr)

[1 2 5 7 8]


In [14]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.concatenate((arr1,arr2))
result

array([1, 2, 3, 4, 5, 6])

### Task 7

In [15]:
oned = np.array([1,2,3,4,5,6])
two=oned.reshape((2,3))
oned

array([1, 2, 3, 4, 5, 6])

In [16]:
column_vector = oned[:,np.newaxis]
column_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [17]:
row_vector = np.expand_dims(oned, axis=0)
next_expand = np.expand_dims(row_vector,axis=1)
next_expand

array([[[1, 2, 3, 4, 5, 6]]])

###  expand dimensions practice

In [18]:


array = np.random.randint(1,20,size=(2,2,3))
print(array)
print(array.ndim)
print(array.shap)

[[[13  2  7]
  [ 9  5  7]]

 [[17 17 14]
  [11 18  2]]]
3


AttributeError: 'numpy.ndarray' object has no attribute 'shap'

In [45]:
### add dimension using new axis
new_one = array[np.newaxis,:]
new_one

array([[[[12,  2, 14],
         [ 3,  9, 13]],

        [[14,  2,  3],
         [ 8,  7, 16]]]])

In [48]:
## new dimension usig expand_dim
expnadone = np.expand_dims(array,axis=1)
expnadone

array([[[[12,  2, 14],
         [ 3,  9, 13]]],


       [[[14,  2,  3],
         [ 8,  7, 16]]]])

### Task 7

In [ ]:
array1d = np.array([1,2,3,4,5,6])
print(array1d.size)
arra2 = array1d.reshape((2,3))
print(arra2)
print(array1d)

6
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [22]:
arr3d = np.random.randint(1,20,size=((2,2,3)))
arr3d

array([[[11,  2, 11],
        [ 4, 13, 16]],

       [[ 8, 19,  7],
        [19,  8,  4]]])

In [24]:
print(arr3d[:,1,:])

[[ 4 13 16]
 [19  8  4]]
