In [4]:
import numpy as np


In [5]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
b=a[1:10:2]
b

array([ 2,  4,  6,  8, 10])

In [7]:
b[1] = 100
b

array([  2, 100,   6,   8,  10])

In [8]:
a

array([  1,   2,   3, 100,   5,   6,   7,   8,   9,  10])

In [9]:
a**2

array([    1,     4,     9, 10000,    25,    36,    49,    64,    81,
         100])

In [10]:
#Take the sign
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.50636564, -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [20]:
a = np.zeros((2,3))
print(a)

b= np.full((2,3),2)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[2 2 2]
 [2 2 2]]


In [18]:
a*b

array([[0., 0., 0.],
       [0., 0., 0.]])

##### Statistics

In [35]:
stats = np.array([[1,7,3],[4,5,6]])
stats

array([[1, 7, 3],
       [4, 5, 6]])

In [36]:
np.min(stats, axis=0)

array([1, 5, 3])

In [31]:
np.sum(stats,axis=0)

array([5, 7, 9])

##  Reorganizing arrays

In [44]:
before  = np.random.randint(1, 7, size=(6,2))
print(before)

[[5 2]
 [3 1]
 [2 6]
 [2 4]
 [2 6]
 [6 5]]


In [45]:
before.shape

(6, 2)

In [48]:
before.reshape((3,4))

array([[5, 2, 3, 1],
       [2, 6, 2, 4],
       [2, 6, 6, 5]])